package artifacts

import (
	"time"
)

// ModuleBundle represents a self-contained, verifiable package of a capability.
// It is the atomic unit of distribution in the Supply Chain.
type ModuleBundle struct {
	Manifest   ModuleManifest `json:"manifest"`
	SourceBlob []byte         `json:"source_blob"` // The actual code (wasm/go plugin)
	Signatures []Signature    `json:"signatures"`  // Mutli-sig support
}

// ModuleManifest describes the metadata and interface of a module.
type ModuleManifest struct {
	Name         string            `json:"name"`
	Version      string            `json:"version"`
	Capabilities []string          `json:"capabilities"` // Provided Tools
	Dependencies []string          `json:"dependencies"` // Required Tools
	Permissions  []string          `json:"permissions"`  // Requested Scopes
	Authors      []string          `json:"authors"`
	License      string            `json:"license"`
	Tags         map[string]string `json:"tags,omitempty"`
}

// Signature wraps a cryptographic signature.
type Signature struct {
	KeyID     string    `json:"key_id"`
	Signature string    `json:"signature"`
	Timestamp time.Time `json:"timestamp"`
}

// MissingOrgansReport deterministic report identifying missing capabilities.
// Generated by the Planner when existing tools cannot fulfill an Obligation.
type MissingOrgansReport struct {
	ID             string    `json:"id"`
	ObligationID   string    `json:"obligation_id"`
	MissingTools   []string  `json:"missing_tools"`
	SuggestedPacks []string  `json:"suggested_packs,omitempty"`
	Timestamp      time.Time `json:"timestamp"`
}

// PowerDeltaReport calculates the impact of an applied change (e.g., install).
type PowerDeltaReport struct {
	ID            string    `json:"id"`
	ActionID      string    `json:"action_id"`      // Link to the Action that caused this
	PreviousPower int       `json:"previous_power"` // Count of tools before
	NewPower      int       `json:"new_power"`      // Count of tools after
	AddedTools    []string  `json:"added_tools"`
	RemovedTools  []string  `json:"removed_tools"`
	Timestamp     time.Time `json:"timestamp"`
}
