// ─── HELM HTML Evidence Report ───────────────────────────────────────────────
// Single-file, self-contained HTML report with embedded CSS and JSON payload.

import { writeFileSync } from "node:fs";

import { GATE_NAMES } from "./gates.js";
import type { VerificationResult } from "./types.js";

/**
 * Generate a single-file HTML evidence report.
 */
export function renderHtmlReport(result: VerificationResult, outputPath: string): void {
    const verdictColor = result.verdict === "PASS" ? "#22c55e" : "#ef4444";
    const verdictEmoji = result.verdict === "PASS" ? "✅" : "❌";

    const gateRows = result.gates.gateResults
        .map((g) => {
            const status = g.pass
                ? '<span style="color:#22c55e">✓ PASS</span>'
                : '<span style="color:#ef4444">✗ FAIL</span>';
            const name = GATE_NAMES[g.gate_id] ?? g.gate_id;
            const reasons = g.pass
                ? ""
                : `<div class="fail-reasons">${g.reasons.join("; ")}</div>`;
            return `<tr>
				<td class="mono bold">${g.gate_id}</td>
				<td>${name}</td>
				<td>${status}</td>
				<td class="mono right">${g.metrics.duration_ms}ms</td>
				<td>${reasons}</td>
			</tr>`;
        })
        .join("\n");

    const failedHashRows = result.hash_chain.failedEntries
        .map(
            (e) => `<tr>
			<td class="mono">${e.path}</td>
			<td class="mono small">${e.expected.substring(0, 16)}…</td>
			<td class="mono small">${e.actual.substring(0, 16)}…</td>
		</tr>`,
        )
        .join("\n");

    const json = JSON.stringify(result, null, 2);

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>HELM Evidence Report — ${result.verdict}</title>
<style>
:root{--bg:#0a0a0a;--fg:#e5e5e5;--muted:#737373;--border:#262626;--card:#141414;--accent:${verdictColor}}
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',system-ui,sans-serif;background:var(--bg);color:var(--fg);line-height:1.6;padding:2rem;max-width:960px;margin:0 auto}
h1{font-size:1.5rem;font-weight:700;margin-bottom:.5rem;display:flex;align-items:center;gap:.5rem}
h2{font-size:1.1rem;font-weight:600;margin:2rem 0 1rem;border-bottom:1px solid var(--border);padding-bottom:.5rem}
.badge{display:inline-block;padding:4px 16px;border-radius:9999px;font-weight:700;font-size:.9rem;background:${verdictColor}20;color:${verdictColor};border:1px solid ${verdictColor}40}
.card{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:1rem 1.25rem;margin:.75rem 0}
.meta{display:grid;grid-template-columns:140px 1fr;gap:.5rem;font-size:.9rem}
.meta dt{color:var(--muted);font-weight:500}
.meta dd{font-family:monospace;word-break:break-all}
table{width:100%;border-collapse:collapse;font-size:.9rem}
th{text-align:left;padding:8px 12px;border-bottom:2px solid var(--border);color:var(--muted);font-weight:500;font-size:.8rem;text-transform:uppercase;letter-spacing:.05em}
td{padding:8px 12px;border-bottom:1px solid var(--border)}
.check{display:flex;align-items:center;gap:.5rem;padding:.5rem 0}
.check-pass{color:#22c55e}
.check-fail{color:#ef4444}
.check-label{font-weight:500;min-width:140px}
.check-detail{color:var(--muted);font-size:.9rem}
.mono{font-family:monospace}
.bold{font-weight:600}
.right{text-align:right}
.small{font-size:.85em}
.fail-reasons{color:#ef4444;font-size:.85em;margin-top:4px}
details{margin:2rem 0}
details summary{cursor:pointer;color:var(--muted);font-size:.85rem}
pre{background:var(--card);border:1px solid var(--border);border-radius:8px;padding:1rem;overflow-x:auto;font-size:.8rem;margin-top:.5rem}
footer{margin-top:3rem;padding-top:1rem;border-top:1px solid var(--border);color:var(--muted);font-size:.8rem;text-align:center}
footer a{color:var(--muted)}
</style>
</head>
<body>
<h1>${verdictEmoji} HELM Evidence Report</h1>
<p style="color:var(--muted);margin-bottom:1.5rem">Generated by <code>@mindburn/helm</code> v3 — Verifiable AI Governance</p>

<div class="card">
<dl class="meta">
<dt>Verdict</dt><dd><span class="badge">${result.verdict}</span></dd>
<dt>Manifest Root</dt><dd>${result.roots.manifest_root_hash}</dd>
<dt>Merkle Root</dt><dd>${result.roots.merkle_root}</dd>
<dt>Evidence</dt><dd>${result.evidence}</dd>
<dt>Profile</dt><dd>${result.profile}</dd>
<dt>Level</dt><dd>${result.gates.level}</dd>
<dt>Duration</dt><dd>${result.timing_ms}ms</dd>
</dl>
</div>

<h2>Verification Checks</h2>
<div class="card">
<div class="check"><span class="${result.structure.pass ? "check-pass" : "check-fail"}">${result.structure.pass ? "✓" : "✗"}</span><span class="check-label">Structure</span><span class="check-detail">${result.structure.dirCount} dirs, ${result.structure.hasIndex ? "00_INDEX ✓" : "00_INDEX ✗"}, ${result.structure.hasScore ? "01_SCORE ✓" : "01_SCORE ✗"}</span></div>
<div class="check"><span class="${result.hash_chain.pass ? "check-pass" : "check-fail"}">${result.hash_chain.pass ? "✓" : "✗"}</span><span class="check-label">Hash Chain</span><span class="check-detail">${result.hash_chain.verifiedEntries}/${result.hash_chain.totalEntries} entries verified</span></div>
<div class="check"><span class="${result.signature.pass ? "check-pass" : "check-fail"}">${result.signature.pass ? "✓" : "✗"}</span><span class="check-label">Signature</span><span class="check-detail">${result.signature.pass ? `${result.signature.signerID ?? "valid"}` : result.signature.reason ?? "failed"}</span></div>
<div class="check"><span class="${result.gates.pass ? "check-pass" : "check-fail"}">${result.gates.pass ? "✓" : "✗"}</span><span class="check-label">Gates</span><span class="check-detail">${result.gates.passedGates}/${result.gates.totalGates} passed (${result.gates.level})</span></div>
<div class="check"><span class="${result.attestation.pass ? "check-pass" : "check-fail"}">${result.attestation.pass ? "✓" : "✗"}</span><span class="check-label">Attestation</span><span class="check-detail">${result.attestation.verified ? "Ed25519 verified" : result.attestation.reason ?? "not checked"}</span></div>
</div>

<h2>Gate Results</h2>
<div class="card" style="padding:0;overflow-x:auto">
<table>
<thead><tr><th>Gate</th><th>Name</th><th>Status</th><th class="right">Duration</th><th>Details</th></tr></thead>
<tbody>${gateRows}</tbody>
</table>
</div>

${result.hash_chain.failedEntries.length > 0
            ? `<h2>Failed Hash Entries</h2>
<div class="card" style="padding:0;overflow-x:auto">
<table>
<thead><tr><th>Path</th><th>Expected</th><th>Actual</th></tr></thead>
<tbody>${failedHashRows}</tbody>
</table>
</div>`
            : ""
        }

<details>
<summary>Raw JSON payload (click to expand)</summary>
<pre><code>${json.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</code></pre>
</details>

<footer>
HELM — Models propose. The kernel disposes.<br>
<a href="https://github.com/Mindburn-Labs/helm-oss">github.com/Mindburn-Labs/helm-oss</a>
</footer>
</body>
</html>`;

    writeFileSync(outputPath, html, "utf-8");
}
