package main

import (
	"context"
	"encoding/hex"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

// runOnboardCmd implements `helm onboard` — one-command local setup.
//
// It initializes a SQLite-backed local store, generates an Ed25519 trust root,
// and prints deterministic next steps. Zero external dependencies required.
//
// Exit codes:
//
//	0 = success
//	2 = config error
func runOnboardCmd(args []string, stdout, stderr io.Writer) int {
	cmd := flag.NewFlagSet("onboard", flag.ContinueOnError)
	cmd.SetOutput(stderr)

	var (
		yes     bool
		dataDir string
	)

	cmd.BoolVar(&yes, "yes", false, "Skip interactive confirmation")
	cmd.StringVar(&dataDir, "data-dir", "data", "Directory for HELM data (SQLite, keys, evidence)")

	if err := cmd.Parse(args); err != nil {
		return 2
	}

	// Banner
	fmt.Fprintf(stdout, "\n%s🚀 HELM Onboard%s\n", ColorBold+ColorBlue, ColorReset)
	fmt.Fprintf(stdout, "%s   Models propose. The kernel disposes.%s\n\n", ColorGray, ColorReset)

	// Step 1: Create data directory
	fmt.Fprintf(stdout, "%s[1/4]%s Creating data directory...  ", ColorBold, ColorReset)
	if err := os.MkdirAll(filepath.Join(dataDir, "artifacts"), 0750); err != nil {
		fmt.Fprintf(stderr, "\n❌ Failed: %v\n", err)
		return 2
	}
	if err := os.MkdirAll(filepath.Join(dataDir, "evidence"), 0750); err != nil {
		fmt.Fprintf(stderr, "\n❌ Failed: %v\n", err)
		return 2
	}
	fmt.Fprintf(stdout, "%s✓%s %s\n", ColorGreen, ColorReset, dataDir)

	// Step 2: Initialize SQLite
	fmt.Fprintf(stdout, "%s[2/4]%s Initializing local store...  ", ColorBold, ColorReset)
	ctx := context.Background()
	db, _, _, err := setupLiteMode(ctx)
	if err != nil {
		fmt.Fprintf(stderr, "\n❌ Failed: %v\n", err)
		return 2
	}
	defer db.Close()
	fmt.Fprintf(stdout, "%s✓%s SQLite at %s/helm.db\n", ColorGreen, ColorReset, dataDir)

	// Step 3: Generate Ed25519 trust root
	fmt.Fprintf(stdout, "%s[3/4]%s Generating trust root...    ", ColorBold, ColorReset)
	signer, err := loadOrGenerateSigner()
	if err != nil {
		fmt.Fprintf(stderr, "\n❌ Failed: %v\n", err)
		return 2
	}
	pubKeyHex := hex.EncodeToString(signer.PublicKeyBytes())
	fmt.Fprintf(stdout, "%s✓%s Ed25519 %s...%s\n", ColorGreen, ColorReset, pubKeyHex[:16], pubKeyHex[len(pubKeyHex)-8:])

	// Step 4: Create helm.yaml if it doesn't exist
	fmt.Fprintf(stdout, "%s[4/4]%s Writing configuration...    ", ColorBold, ColorReset)
	configPath := "helm.yaml"
	if _, err := os.Stat(configPath); os.IsNotExist(err) {
		config := `# HELM Configuration — generated by 'helm onboard'
version: "0.2"
kernel:
  profile: CORE
  store: sqlite
  data_dir: data
trust:
  root_public_key: "` + pubKeyHex + `"
`
		if err := os.WriteFile(configPath, []byte(config), 0600); err != nil {
			fmt.Fprintf(stderr, "\n❌ Failed: %v\n", err)
			return 2
		}
		fmt.Fprintf(stdout, "%s✓%s helm.yaml\n", ColorGreen, ColorReset)
	} else {
		fmt.Fprintf(stdout, "%s✓%s helm.yaml (exists)\n", ColorGreen, ColorReset)
	}

	// Success + next steps
	fmt.Fprintf(stdout, "\n%s────────────────────────────────────────────────%s\n", ColorCyan, ColorReset)
	fmt.Fprintf(stdout, "%s✅ HELM is ready.%s\n\n", ColorBold+ColorGreen, ColorReset)
	fmt.Fprintf(stdout, "%sNext steps:%s\n\n", ColorBold, ColorReset)

	fmt.Fprintf(stdout, "  %s1.%s Run the starter organization demo:\n", ColorBold+ColorCyan, ColorReset)
	fmt.Fprintf(stdout, "     %shelm demo organization --template starter%s\n\n", ColorBold, ColorReset)

	fmt.Fprintf(stdout, "  %s2.%s Start the governance proxy:\n", ColorBold+ColorCyan, ColorReset)
	fmt.Fprintf(stdout, "     %shelm proxy --upstream https://api.openai.com/v1%s\n\n", ColorBold, ColorReset)

	fmt.Fprintf(stdout, "  %s3.%s Start the MCP server:\n", ColorBold+ColorCyan, ColorReset)
	fmt.Fprintf(stdout, "     %shelm mcp serve%s\n\n", ColorBold, ColorReset)

	fmt.Fprintf(stdout, "%sDocs:%s https://github.com/Mindburn-Labs/helm-oss\n\n", ColorGray, ColorReset)

	return 0
}

func init() {
	Register(Subcommand{Name: "onboard", Usage: "One-command local setup (SQLite + keys + config)", RunFn: runOnboardCmd})
}
