package contracts

import "time"

// GoalSpec represents a goal specification for agent execution.
//
//nolint:govet // fieldalignment: struct layout is human-readable
type GoalSpec struct {
	GoalID          string            `json:"goal_id"`
	OriginalIntent  string            `json:"original_intent"`
	RoutingStrategy string            `json:"routing_strategy"`
	Constraints     map[string]any    `json:"constraints"`
	SuccessCriteria string            `json:"success_criteria"`
	InputContext    map[string]string `json:"input_context"`
}

// ActionStep represents a single step in an action plan.
//
//nolint:govet // fieldalignment: struct layout is human-readable
type ActionStep struct {
	StepID           string   `json:"step_id"`
	Description      string   `json:"description"`
	Action           Action   `json:"action"`
	RequiredEvidence []string `json:"required_evidence"`
}

// AgentActionPlan represents a plan generated by an agent.
//
//nolint:govet // fieldalignment: struct layout is human-readable
type AgentActionPlan struct {
	GoalID      string       `json:"goal_id"`
	Steps       []ActionStep `json:"steps"`
	GeneratedAt time.Time    `json:"generated_at"`
}

// EvidenceBundle represents evidence collected for a step.
//
//nolint:govet // fieldalignment: struct layout is human-readable
type EvidenceBundle struct {
	StepID    string            `json:"step_id"`
	Items     map[string]string `json:"items"`
	RiskScore float64           `json:"risk_score"`
	Timestamp time.Time         `json:"timestamp"`
	Artifacts []string          `json:"artifacts"`
}

// GenomePatchProposal represents a proposed patch to the genome.
type GenomePatchProposal struct {
	PlanID       string `json:"plan_id"`
	PatchID      string `json:"patch_id"`
	Description  string `json:"description"`
	Reasoning    string `json:"reasoning"`
	NewPolicyCEL string `json:"new_policy_cel"`
	Changes      string `json:"changes"`
}

// StepResult represents the result of a single step execution.
//
//nolint:govet // fieldalignment: struct layout is human-readable
type StepResult struct {
	StepID  string         `json:"step_id"`
	Success bool           `json:"success"`
	Output  map[string]any `json:"output,omitempty"`
	Error   string         `json:"error,omitempty"`
}

// ExecutionReport represents a complete execution report.
//
//nolint:govet // fieldalignment: struct layout is human-readable
type ExecutionReport struct {
	PlanID      string       `json:"plan_id"`
	Status      string       `json:"status"`
	FinishedAt  time.Time    `json:"finished_at"`
	StepResults []StepResult `json:"step_results"`
}
